
server:
  port: 8080


spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/？
      username: ？
      password: ？
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      validation-query: SELECT 'x'
      test-on-return: false
      test-on-borrow: false
      test-while-idle: false
      pool-prepared-statements: true
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      max-pool-prepared-statement-per-connection-size: 20
      min-evictable-idle-time-millis: 25200000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      filter: mergeStat
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB


mybatis:
  type-aliases-package: com.daydao.assmline.model
  mapper-locations: classpath:mapper/*.xml



logback:
  logdir: "E:/logs/"
  appname: assmline